site_name: FiveR - Hulpdiensten Nederland
site_url: 'https://fivernl.github.io/fivernl.github.io/'
site_description: 'APV & meer van FiveR'
site_author: 'stijn_gamet'

repo_name: 'fivernl/fivernl.github.io'
repo_url: 'https://github.com/fivernl/fivernl.github.io/'

copyright: Copyright &copy; 2023 FiveR - Hulpdiensten Nederland

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  language: nl
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - header.autohide
    - toc.follow

nav:
  - Home: index.md
  - Algemene Plaatselijke Verordening: apv.md
  - Wetboek: wetboek.md

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics: FiveR - Hulpdiensten Nederland
    actions:
      - accept
      - manage
      - reject
